# Use the official PostgreSQL 13.4 image from Docker Hub
FROM postgres:13.4

# Expose the PostgreSQL port
EXPOSE 5432

# Volume to persist database data
VOLUME ["/var/lib/postgresql/data"]

# Command to run PostgreSQL
CMD ["postgres"]